batch_size: 4
iters: 80000

train_dataset:
  type: brats2020
  dataset_root: data/zcross/
  transforms:
    - type: RandomHorizontalFlip
    - type: RandomVerticalFlip
  mode: train

val_dataset:
  type: brats2020
  dataset_root: data/zcross/
  transforms:
    - type: RandomHorizontalFlip
    - type: RandomVerticalFlip
  mode: val


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
      weight: [0.1, 0.3, 0.3, 0.3]
  coef: [1]
