batch_size: 2
iters: 800000

train_dataset:
  type: brats2020_npz_compress_ignore
  dataset_root: data/zcross_P_compress
  transforms:
    - type: RandomHorizontalFlip
  mode: train

val_dataset:
  type: brats2020_npz_compress_ignore
  dataset_root: data/zcross_P_compress
  transforms:
    - type: RandomHorizontalFlip
  mode: val


optimizer:
  type: AdamW
  weight_decay: 0.01

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.00006
  end_lr: 0
  power: 1.0

loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: DiceLoss
      coef: [0.3, 0.7]
  coef: [1]
