batch_size: 16
iters: 900000

train_dataset:
  type: brats2020_ignore
  dataset_root: data/zcross
  transforms:
    - type: RandomHorizontalFlip
  mode: train

val_dataset:
  type: brats2020_ignore
  dataset_root: data/zcross
  transforms:
    - type: RandomHorizontalFlip
  mode: val



optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: DiceLoss
      coef: [0.3, 0.7]
  coef: [1]
