_base_: '../_base_/brats2020Adwm1_missloss.yml'

batch_size: 2
iters: 800000

model:
  type: SegNet
  num_classes: 4
  in_channels: 4
  pretrained: Null #output_segnet_brats/best_model/model.pdparams
