_base_: '../_base_/brats2020Adwm1_missloss.yml'
batch_size: 2
iters: 800000


model:
  type: FastFCN
  backbone:
    type: ResNet50_vd
    output_stride: 8
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
  num_classes: 4
  num_codes: 32
  mid_channels: 512
  use_jpu: True
  aux_loss: True
  use_se_loss: True
  add_lateral: True

loss:
  types:
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
    - type: SECrossEntropyLoss
  coef: [1, 0.4, 0.2]
