_base_: '../_base_/brats2020Adwm1_missloss.yml'

batch_size: 8
iters: 900000

model:
  type: UNet
  num_classes: 4
  in_channels: 4
  use_deconv: False
  pretrained: Null #./output_unet/iter_520000/model.pdparams
