_base_: '../_base_/brats2020cross1_ignore.yml'

batch_size: 2
iters: 800000

model:
  type: UNet
  num_classes: 4
  in_channels: 4
  use_deconv: False
  pretrained: ./output_unet_ignore/iter_300000/model.pdparams
