_base_: '../_base_/brats2020.yml'

batch_size: 2
iters: 900000

model:
  type: UNet
  num_classes: 4
  in_channels: 4
  use_deconv: False
  pretrained: ./output_unet_ignore_plus/iter_460000/model.pdparams
