_base_: '../_base_/brats2020Adwm1_missloss.yml'

batch_size: 2
iters: 800000

model:
  type: UPerNet
  backbone:
    type: SwinTransformer_tiny_patch4_window7_224
    in_channels: 4
  backbone_indices: [0, 1, 2, 3]
  channels: 256
  dropout_prob: 0.3
  enable_auxiliary_loss: False
