_base_: '../_base_/brats2020Adwm1_missloss.yml'

batch_size: 2
iters: 800000

model:
  type: UPerNet
  backbone:
    type: CSwin_residual_uper
    in_channels: 4
    num_classes: 4
  num_classes: 4
  backbone_indices: [0, 1, 2, 3]
  channels: 256
  dropout_prob: 0.3
  enable_auxiliary_loss: False
