_base_: '../_base_/brats2020Adwm1_missloss.yml'

batch_size: 8
iters: 800000

model:
  type: DANet
  backbone:
    type: ResNet50_vd
    output_stride: 8
    pretrained: Null #https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
  num_classes: 4
  backbone_indices: [2, 3]
  pretrained: Null #output_danet_resnet50/best_model/model.pdparams


loss:
  types:
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
  coef: [1, 1, 1, 0.4]