_base_: '../_base_/brats2020.yml'

batch_size: 2
iters: 900000

model:
  type: SwinTransformer_conv_Unet1_small
  num_classes: 4
  in_channels: 4
  pretrained: ./output_SwinTransformer_conv_Unet1_small/iter_8264/iter_90000/model.pdparams
