_base_: '../_base_/brats2020Adwm1_missloss.yml'

batch_size: 2
iters: 800000

model:
  type: SwinTransformerUnet1_origin
  num_classes: 4
  in_channels: 4
  pretrained: Null #./output_swin_transformer_unet1_small_P/iter_180000/model.pdparams
