_base_: '../_base_/brats2020Adwm1_missloss.yml'

batch_size: 2
iters: 900000

model:
  type: SwinTransformerUnet1_small
  num_classes: 4
  in_channels: 4
  pretrained: ./output_swin_transformer_unet1_small/iter_320000/model.pdparams
