_base_: 'configs/_base_/brats2020Adwm1_missloss_PPPPPPPPPPPPNew.yml'

batch_size: 16
iters: 900000

model:
  type: SwinTransformerUnet1_small_residual_PP
  num_classes: 4
  in_channels: 4
  pretrained: Null # ./output_swin_transformer_unet1_small_residual/iter_200000/model.pdparams
