_base_: '../_base_/brats2020Adwm1_missloss_PPPPPPPPPPPPNew.yml'

batch_size: 4
iters: 900000

model:
  type: SwinTransformerUnet1_small_residual_PP
  num_classes: 4
  in_channels: 4
  pretrained: Null #./output_swin_transformer_unet1_small_residual_PP/iter_450000/model.pdparams
