_base_: '../_base_/brats2020Adwm1_missloss.yml'

batch_size: 8
iters: 900000

model:
  type: SwinTransformerUnet1_base
  num_classes: 4
  in_channels: 4
  pretrained: Null #./output_swin_transformer_unet1_base/iter_760000/model.pdparams
