_base_: '../_base_/brats2020Adwm1_missloss.yml'

batch_size: 8
iters: 900000

model:
  type: SwinTransformerUnet1_small_residual_PP
  num_classes: 4
  in_channels: 4
  pretrained: ./output_swin_transformer_unet1_small_residual_PP_plus1/best_model/model.pdparams
