_base_: '../_base_/brats2020Adwm1_missloss.yml'

batch_size: 8
iters: 900000

model:
  type: UNetPlusPlus
  in_channels: 4
  num_classes: 4
  use_deconv: False
  align_corners: False
  is_ds: True
  pretrained: Null
