_base_: '../_base_/brats2020.yml'

batch_size: 4
iters: 800000

model:
  type: UNetPlusPlus
  in_channels: 4
  num_classes: 4
  use_deconv: False
  align_corners: False
  pretrained: Null
  is_ds: True
